# frozen_string_literal: true

require_relative "custom_matchers/set_processor_option"
require_relative "custom_matchers/use_batch_processor_strategy"
require_relative "custom_matchers/use_default_job_class"
require_relative "custom_matchers/use_default_processor"
require_relative "custom_matchers/use_job_class"
require_relative "custom_matchers/use_parallel_processor"
require_relative "custom_matchers/use_sequential_processor"
